### ISSUE TITLE
User not authorized to access this resource

### ISSUE THREAD

**Issue by QandnotU** [kovapatrik/homebridge-blueair-purifier#15]
**Describe The Bug:**
Recently installed the plugin and when starting Homebridge, I'm getting the following error below.

**To Reproduce:**
Restart HomeBridge

**Expected behavior:**
[10/29/2024, 10:34:29 AM] [blueair-purifier] Error getting initial device states: Error: API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource"}
    at BlueAirAwsApi.apiCall (/usr/local/lib/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:252:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at BlueAirAwsApi.getDeviceStatus (/usr/local/lib/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:148:18)
    at BlueAirPlatform.getInitialDeviceStates (/usr/local/lib/node_modules/homebridge-blueair-purifier/src/platform.ts:84:23)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-blueair-purifier/src/platform.ts:45:7)
[10/29/2024, 10:34:30 AM] [blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource"}. Retrying in 5 seconds...
[10/29/2024, 10:34:47 AM] [blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource"}. Retrying in 5 seconds...
[10/29/2024, 10:35:04 AM] [blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource"}. Retrying in 5 seconds...

**Plugin Config:**

{
    "username": "removed",
    "password": "removed",
    "region": "USA",
    "accountUuid": "17e4eca2-a4e6-42a5-a919-ff2400ed2446",
    "verboseLogging": true,
    "uiDebug": true,
    "devices": [
        {
            "id": "1",
            "name": "Master Blueair",
            "model": "Blue Pure 511i Max",
            "serialNumber": "111117800201111210028217",
            "filterChangeLevel": 10,
            "led": true,
            "nightMode": true
        }
    ],
    "platform": "blueair-purifier"
}

**Environment:**

* **Plugin Version**: 1.0.12
* **Homebridge Version**: 1.8.5
* **Node.js Version**: v22.11.0
* **NPM Version**: 10.9.0
* **Operating System**: macOS Sequoia

**Comment by kovapatrik** [comment]
You might have misstyped your username/password or you have to select another region.

**Comment by kovapatrik** [comment]
Or maybe your devices are attached to a different account?

**Comment by QandnotU** [comment]
@kovapatrik I'm a bonehead, when I discovered the device, I never clicked "Add", I just added the UUID and added it manually. Sorry for the false alarm.

I did want to confirm everything is working great on the Blue Pure 511i Max, which is not on your supported devices list, so not sure if this gives you enough confidence to add that to the list.

**Comment by kovapatrik** [comment]
Oh:D no worries!

Absolutely, thanks for the feedback!
