### ISSUE TITLE
API call error with status 229

### ISSUE THREAD

**Issue by nebosphere19** [kovapatrik/homebridge-blueair-purifier#17]
**Describe Your Problem:**
Getting this over and over in error logs: [11/11/2024, 11:52:55 AM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
see above
**Plugin Config:**

```json
.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by jwall87** [comment]
Getting the same issue. I had it working so well over the weekend!

`[11/12/2024, 6:32:46 PM] [homebridge-blueair-purifier] Error getting initial device states: Error: API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}
    at BlueAirAwsApi.apiCall (/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:252:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlueAirAwsApi.getDeviceStatus (/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:148:18)
    at BlueAirPlatform.getInitialDeviceStates (/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:84:23)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:45:7)`

**Comment by jwall87** [comment]
Update - I increased the polling interval to 45000 (45 seconds). This is probably much more than what is required but it helped solve the issue for now. I'm guessing when I tried this last night that I was already at my max requests for the day. Probably need some trial and error to see what the new polling amount can be. Guessing BlueAir changed it to a higher threshold.

**Comment by kovapatrik** [comment]
Yes, you must deinitely has to wait after you get rate limited. Maybe I need to implement a logic to stop doing requests until a set time.

**Comment by samuelbeaulieu** [comment]
I had the same error all morning today. I was at 15000, then bumped it to 30000 -> 45000 -> 60000. It was still not working. I then went all the way to 300000 (5 mins) and the error went away after restarting the child bridge. I'll keep it this way for now.

**Comment by kovapatrik** [comment]
Keep in mind you have to wait for a time before the rate limiting lifted from you (I don't know the exact time as this is set by the Blueair servers). So wouldn't handle your case as a fact.

**Comment by samuelbeaulieu** [comment]
Oh! I see. I didn't take that into consideration, you're right! 🤦🏻‍♂️

**Comment by yjeanrenaud** [comment]
how come this also occures when the discovery process was not yet completed?
