### ISSUE TITLE
Can't get HomeBridge to pull in my devices

### ISSUE THREAD

**Issue by gautamsethi** [kovapatrik/homebridge-blueair-purifier#18]
**Describe Your Problem:**
I installed your plugin (thank you for developing it!) and put in my login credentials but HomeBridge is unable to pull in my purifier. I have already added one of my BlueAir purifiers to my account on the BlueAir website. I'd appreciate any suggestions you might have to fix this issue.

**Logs:**

```
[11/30/2024, 1:12:20 PM] [blueair-purifier] Error getting initial device states: Error: API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}
    at BlueAirAwsApi.apiCall (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:252:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlueAirAwsApi.getDeviceStatus (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:148:18)
    at BlueAirPlatform.getInitialDeviceStates (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:84:23)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:45:7)
[11/30/2024, 1:12:20 PM] [blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...
```

**Plugin Config:**

```json
{
    "username": "gautamsethi@gmail.com",
    "password": "LBBf3GZ3d8***hidden***sdfDFQnpw8QU",
    "region": "USA",
    "devices": [
        {
            "id": "b4:8a:0a:95:43:3c",
            "name": "Protect 7470i",
            "model": "Protect 7470i",
            "serialNumber": "110582600300110210000252",
            "filterChangeLevel": 0,
            "led": true,
            "airQualitySensor": true,
            "temperatureSensor": true,
            "germShield": true,
            "nightMode": true
        }
    ],
    "platform": "blueair-purifier"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.0.12
* **Homebridge Version**:v1.8.5
* **Node.js Version**: 
* **NPM Version**: Not sure how to find this
* **Operating System**: macOS

**Comment by kovapatrik** [comment]
You got rate limited. Set the polling rate to a higher number (check the other issues, some users have figured out some rate which looked working)

**Comment by gautamsethi** [comment]
Thank you for your prompt reply.

I set the polling rate at 30000 and that didn't help. When I click on discover devices and put in my credentials, I get this error  (see attachment).

Is the plugin config inputted correctly? I used the MAC address for the id (not sure if that is correct), for example.

<img width="298" alt="Screenshot 2024-11-30 at 1 46 55 PM" src="https://github.com/user-attachments/assets/07313a63-2ce1-46b4-8e26-451cdd9733d2">

**Comment by kovapatrik** [comment]
You have to wait a bit before retrying, that's how rate limiting works. You are blocked for a certain time, this way a server can be secured from any harmful actions.

**Comment by gautamsethi** [comment]
Understood. 

Since the plugin is retrying every few seconds, should I delete the plug in and reinstall it later? Or just leave things as is and check in after a few hours?


[11/30/2024, 1:53:45 PM] [BlueAir] Error getting initial device states: Error: API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}
    at BlueAirAwsApi.apiCall (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:252:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlueAirAwsApi.getDeviceStatus (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:148:18)
    at BlueAirPlatform.getInitialDeviceStates (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:84:23)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:45:7)
[11/30/2024, 1:53:45 PM] [BlueAir] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...
[11/30/2024, 1:54:15 PM] [BlueAir] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...
[11/30/2024, 1:54:46 PM] [BlueAir] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...
[11/30/2024, 1:55:16 PM] [BlueAir] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...
[11/30/2024, 1:55:46 PM] [BlueAir] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 229: , {"message":"There are too many calls, please try again later"}. Retrying in 5 seconds...

**Comment by kovapatrik** [comment]
I think it should work If you leave this as is, but it's safer to delete the plugin and reinstall it later.

**Comment by gautamsethi** [comment]
Thanks. I deleted it. Will try it tonight.

Is the info in the input config correctly inputted? I'm not sure what goes in the id and name fields. I reproduce it here:

{
    "username": "gautamsethi@gmail.com",
    "password": "LBBf3GZ3d8***hidden***sdfDFQnpw8QU",
    "region": "USA",
    "devices": [
        {
            "id": "b4:8a:0a:95:43:3c",
            "name": "Protect 7470i",
            "model": "Protect 7470i",
            "serialNumber": "110582600300110210000252",
            "filterChangeLevel": 0,
            "led": true,
            "airQualitySensor": true,
            "temperatureSensor": true,
            "germShield": true,
            "nightMode": true
        }
    ],
    "platform": "blueair-purifier"
}

**Comment by kovapatrik** [comment]
Those fields should be filled when the discovery is done. I think it's better to delete this configuration and redo the discovery later which will fill all fields.

**Comment by gautamsethi** [comment]
The discovery only asks for username, password, and region. Not sure how changing the polling rate will help but obviously you're the one who knows how the plugin works. When I reinstall, I'll reset the polling rate to 30000 and then do the discovery, leaving everything else blank.

**Comment by kovapatrik** [comment]
Yes, but it would be convenient if a discovery process would automatically create your configuration so you don't have to copy paste it, isn't?:DD So yeah, the discovery process, at the end, created the entries in your config file.

**Comment by gautamsethi** [comment]
It works perfectly now. I didn't have to change a thing. Thank you so much!
