### ISSUE TITLE
invalid loginID or password & Account temporarily locked out

### ISSUE THREAD

**Issue by cnyanhao** [kovapatrik/homebridge-blueair-purifier#19]
**Describe Your Problem:**
- First few errors: invalid loginID or password.
- Then consistent errors: Account temporarily locked out.
- Using the blueair account paired with the blue air purifier before.
- The account works on both Blueair app and website.
- Tried pairing after removing the purifier in the Blueair app, but still get the same errors. 

**Logs:**

```
[homebridge-blueair-purifier] Error getting valid devices status, reason:Gigya session error: sessionInfo in response: {"callId":"154e9b6f619047218a5973b22e0e8ef4","errorCode":403042,"errorDetails":"invalid loginID or password","errorMessage":"Invalid LoginID","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2024-12-20T04:11:01.304Z"}. Retrying in 5 seconds...

[homebridge-blueair-purifier] Error getting valid devices status, reason:Gigya session error: sessionInfo in response: {"callId":"da2731d387ae4381abc7b1e1be3cc729","errorCode":403120,"errorDetails":"Account temporarily locked out","errorMessage":"Account Temporarily Locked Out","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2024-12-20T04:14:02.839Z"}. Retrying in 5 seconds...
```

**Plugin Config:**

```json
{
    "username": "username",
    "password": "password",
    "pollingInterval": 45000,
    "platform": "blueair-purifier",
    "_bridge": {
        "username": "0E:80:28:A3:85:6A",
        "port": 52058
    }
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.0.12
* **Homebridge Version**: v1.8.5
* **Node.js Version**: v22.12.0
* **NPM Version**: 10.9.0
* **Operating System**: Raspbian

**Comment by fish-sammy** [comment]
```
[12/5/2025, 5:08:14 PM] [homebridge-blueair-purifier] Missing required configuration options! Please do the device discovery in the configuration UI and/or check your      config.json file
[12/5/2025, 5:08:14 PM] [homebridge-blueair-purifier] Getting initial device states...
[12/5/2025, 5:08:14 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[12/5/2025, 5:08:15 PM] [homebridge-blueair-purifier] Error getting initial device states: Error: API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}
    at BlueAirAwsApi.apiCall (/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:252:17)
    at processTicksAndRejections (node:internal/process/task_queues:103:5)
    at BlueAirAwsApi.getDeviceStatus (/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:148:18)
    at BlueAirPlatform.getInitialDeviceStates (/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:84:23)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:45:7)
[12/5/2025, 5:08:15 PM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}. Retrying in 5 seconds...
[12/5/2025, 5:08:31 PM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}. Retrying in 5 seconds...
[12/5/2025, 5:08:46 PM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}. Retrying in 5 seconds...
[12/5/2025, 5:09:01 PM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}. Retrying in 5 seconds...
[12/5/2025, 5:09:16 PM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}. Retrying in 5 seconds...
[12/5/2025, 5:09:32 PM] [homebridge-blueair-purifier] Error getting valid devices status, reason:API call failed after 3 retries with error: Error: API call error with status 403: Forbidden, {"Message":"User is not authorized to access this resource because no identity-based policy allows the execute-api:Invoke action"}. Retrying in 5 seconds...
```

**Comment by kovapatrik** [comment]
Any news on this?
