### ISSUE TITLE
Blueair 211i login

### ISSUE THREAD

**Issue by rdav65** [kovapatrik/homebridge-blueair-purifier#9]
**Describe Your Problem:**
I'm unable to see device in Homekit. I can't recognize issue from logs below.

**Logs:**

```
[19/07/2024, 08:38:13] [homebridge-blueair-purifier] Gigya session received
[19/07/2024, 08:38:13] [homebridge-blueair-purifier] Gigya JWT received
[19/07/2024, 08:38:13] [homebridge-blueair-purifier] Getting AWS access token...
[19/07/2024, 08:38:14] [homebridge-blueair-purifier] AWS access token received
[19/07/2024, 08:38:14] [homebridge-blueair-purifier] Logged in
[19/07/2024, 08:38:15] [homebridge-blueair-purifier] Error getting initial device states: Error: API call failed after 3 retries with error: Error: API call error with status 502: Bad Gateway, {"message":"Internal server error"}
    at BlueAirAwsApi.apiCall (/var/lib/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:252:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlueAirAwsApi.getDeviceStatus (/var/lib/homebridge/node_modules/homebridge-blueair-purifier/src/api/BlueAirAwsApi.ts:148:18)
    at BlueAirPlatform.getInitialDeviceStates (/var/lib/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:84:23)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-blueair-purifier/src/platform.ts:45:7)
[19/07/2024, 08:38:15] [homebridge-blueair-purifier] Updating devices states...
[19/07/2024, 08:38:16] [homebridge-blueair-purifier] Devices states updated!
[19/07/2024, 08:38:21] [homebridge-blueair-purifier] Updating devices states...
[19/07/2024, 08:38:21] [homebridge-blueair-purifier] Devices states
```

**Plugin Config:**

```json

}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by kovapatrik** [comment]
How did you add the device to Homebridge? Also, is that device still connected to your Blueair account?

**Comment by rdav65** [comment]
HelloI have a raspi homebridge server with 6 plugins. I had been using an unverified Blueair plugin but decided to try this one. The device is visible via WiFi in my account and on the app. I did not understand the errors in the log. Sent from my iPhoneOn Jul 20, 2024, at 12:50 PM, Kovalovszky Patrik ***@***.***> wrote:﻿
How did you add the device to Homebridge? Also, is that device still connected to your Blueair account?

**Comment by kovapatrik** [comment]
My question was how did you add the device in the plugin? My guess is the plugin wants to use a different account from the account the air purifier is connected to. Can you please double check this?

**Comment by rdav65** [comment]
I added the device found in my account using the plugin config. My id and password were accepted, and my device was added. I am just unable to see device when I run platform as a child bridge in Homekit.
________________________________

**Comment by kovapatrik** [comment]
Did you add the child bridge to the Home app?

**Comment by rdav65** [comment]
All is working now. I ended up uninstalling plugin and Blueair child bridges in HomeKit and starting over from scratch. Everything then worked fine. Should’ve done that in the beginning. ThanksSent from my iPhoneOn Jul 29, 2024, at 4:51 PM, Kovalovszky Patrik ***@***.***> wrote:﻿
Did you add the child bridge to the Home app?
